<a href="https://colab.research.google.com/github/sergio-cabrales/python/blob/main/MachineLearning2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install ta

  Created wheel for ta: filename=ta-0.7.0-cp37-none-any.whl size=28716 sha256=b7a1f3faa7fc91a180da740f840ca852693f6de592b34ab0b6f30ab262cec4e2
  Stored in directory: /root/.cache/pip/wheels/dd/88/30/de9553fb54a474eb7480b937cdbb140bdda613d29cf4da7994
Successfully built ta


In [4]:
# Import the libraries
import pandas as pd
import pandas_datareader as web
import numpy as np
import datetime
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from ta import add_all_ta_features
from ta.utils import dropna

In [5]:
# Get the stock quote
df = web.DataReader('AAPL', data_source='yahoo',start='2010-01-01', end='2021-01-01')
df

High         Low  ...       Volume   Adj Close
Date                                ...                         
2010-01-04    7.660714    7.585000  ...  493729600.0    6.583586
2010-01-05    7.699643    7.616071  ...  601904800.0    6.594968
2010-01-06    7.686786    7.526786  ...  552160000.0    6.490066
2010-01-07    7.571429    7.466071  ...  477131200.0    6.478067
2010-01-08    7.571429    7.466429  ...  447610800.0    6.521136
...                ...         ...  ...          ...         ...
2020-12-24  133.460007  131.100006  ...   54930100.0  131.773087
2020-12-28  137.339996  133.509995  ...  124486200.0  136.486053
2020-12-29  138.789993  134.339996  ...  121047300.0  134.668762
2020-12-30  135.990005  133.399994  ...   96452100.0  133.520477
2020-12-31  134.740005  131.720001  ...   99116600.0  132.492020

[2769 rows x 6 columns]

In [7]:
add_all_ta_features(df, open="Open", high="High", low="Low", close="Close", volume="Volume")

/usr/local/lib/python3.7/dist-packages/ta/trend.py:768: RuntimeWarning: invalid value encountered in double_scalars
  dip[i] = 100 * (self._dip[i] / self._trs[i])
/usr/local/lib/python3.7/dist-packages/ta/trend.py:772: RuntimeWarning: invalid value encountered in double_scalars
  din[i] = 100 * (self._din[i] / self._trs[i])


High         Low  ...  others_dlr    others_cr
Date                                ...                         
2010-01-04    7.660714    7.585000  ...         NaN     0.000000
2010-01-05    7.699643    7.616071  ...    0.172744     0.172893
2010-01-06    7.686786    7.526786  ...   -1.603419    -1.420489
2010-01-07    7.571429    7.466071  ...   -0.185042    -1.602734
2010-01-08    7.571429    7.466429  ...    0.662633    -0.948557
...                ...         ...  ...         ...          ...
2020-12-24  133.460007  131.100006  ...    0.768265  1626.629626
2020-12-28  137.339996  133.509995  ...    3.514097  1688.383766
2020-12-29  138.789993  134.339996  ...   -1.340429  1664.571699
2020-12-30  135.990005  133.399994  ...   -0.856324  1649.525753
2020-12-31  134.740005  131.720001  ...   -0.773247  1636.049763

[2769 rows x 89 columns]

In [8]:
# Create the Target column
# df['Target'] = np.where(df['Close'].shift(-1) > df['Close'], 1, 0)
df['Target'] = np.where(df['Close'] > df['Open'], 1, 0)
# Show the data
df

High         Low        Open  ...  others_dlr    others_cr  Target
Date                                            ...                                 
2010-01-04    7.660714    7.585000    7.622500  ...         NaN     0.000000       1
2010-01-05    7.699643    7.616071    7.664286  ...    0.172744     0.172893       0
2010-01-06    7.686786    7.526786    7.656429  ...   -1.603419    -1.420489       0
2010-01-07    7.571429    7.466071    7.562500  ...   -0.185042    -1.602734       0
2010-01-08    7.571429    7.466429    7.510714  ...    0.662633    -0.948557       1
...                ...         ...         ...  ...         ...          ...     ...
2020-12-24  133.460007  131.100006  131.320007  ...    0.768265  1626.629626       1
2020-12-28  137.339996  133.509995  133.990005  ...    3.514097  1688.383766       1
2020-12-29  138.789993  134.339996  138.050003  ...   -1.340429  1664.571699       0
2020-12-30  135.990005  133.399994  135.580002  ...   -0.856324  1649.525753       0
2020-12-31  134.740005  131.720001  134.080002  ...   -0.773247  1636.049763       0

[2769 rows x 90 columns]

In [9]:
#Remove the first 29 days of data
df = df[29:]
# Clean NaN values
# df = dropna(df)
df

High         Low        Open  ...  others_dlr    others_cr  Target
Date                                            ...                                 
2010-02-16    7.274643    7.197143    7.212143  ...    1.495893    -4.957707       1
2010-02-17    7.296786    7.173571    7.292500  ...   -0.418768    -5.354882       0
2010-02-18    7.281786    7.175714    7.201071  ...    0.187423    -5.177328       1
2010-02-19    7.257143    7.182500    7.209286  ...   -0.622840    -5.766087       0
2010-02-22    7.232143    7.113929    7.226429  ...   -0.621754    -6.350172       0
...                ...         ...         ...  ...         ...          ...     ...
2020-12-24  133.460007  131.100006  131.320007  ...    0.768265  1626.629626       1
2020-12-28  137.339996  133.509995  133.990005  ...    3.514097  1688.383766       1
2020-12-29  138.789993  134.339996  138.050003  ...   -1.340429  1664.571699       0
2020-12-30  135.990005  133.399994  135.580002  ...   -0.856324  1649.525753       0
2020-12-31  134.740005  131.720001  134.080002  ...   -0.773247  1636.049763       0

[2740 rows x 90 columns]

In [10]:
#Split tha data set into a feature or independent data set (X) and a Target or dependent data set (Y)
Y = df['Target'].values
Y

array([1, 0, 1, ..., 0, 0, 0])

In [11]:
X = df.drop(columns='Target')
X

High         Low  ...  others_dlr    others_cr
Date                                ...                         
2010-02-16    7.274643    7.197143  ...    1.495893    -4.957707
2010-02-17    7.296786    7.173571  ...   -0.418768    -5.354882
2010-02-18    7.281786    7.175714  ...    0.187423    -5.177328
2010-02-19    7.257143    7.182500  ...   -0.622840    -5.766087
2010-02-22    7.232143    7.113929  ...   -0.621754    -6.350172
...                ...         ...  ...         ...          ...
2020-12-24  133.460007  131.100006  ...    0.768265  1626.629626
2020-12-28  137.339996  133.509995  ...    3.514097  1688.383766
2020-12-29  138.789993  134.339996  ...   -1.340429  1664.571699
2020-12-30  135.990005  133.399994  ...   -0.856324  1649.525753
2020-12-31  134.740005  131.720001  ...   -0.773247  1636.049763

[2740 rows x 89 columns]

In [12]:
X.fillna(X.mean(), inplace=True)

In [13]:
# Split the data again but this time into 80% trading and 20% test
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.1, random_state =2)

In [14]:
# Create and train the decision tree classsifier model
tree = DecisionTreeClassifier().fit(X_train,Y_train)

In [15]:
#Check how well the model did on the trainign data set
print(tree.score(X_train,Y_train))

1.0


In [16]:
#Check how weel the model did on the testing data set
print(tree.score(X_test,Y_test))

0.7956204379562044


In [17]:
#Show the model tree predictions
tree_predictions = tree.predict(X_test)
print(tree_predictions)

[1 1 1 1 1 0 1 1 0 0 1 0 0 0 1 0 0 0 1 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 0 0 0
 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1
 0 1 1 0 1 0 0 0 1 1 0 0 0 1 1 1 0 1 0 0 1 1 0 0 1 0 1 0 0 0 1 0 1 1 1 0 1
 1 0 1 1 0 1 0 0 0 0 1 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 0 0 1 1 1 1 1
 1 1 0 1 0 1 1 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 1 1 1 0 1 1 1 0 0 1 0 0 0 1 1
 1 0 0 1 0 1 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 0 0
 0 0 1 1 0 1 0 1 1 0 0 1 1 1 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0 1
 0 1 0 1 1 1 1 0 1 0 0 1 1 1 1]


In [18]:
Y_test

array([0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1])

In [19]:
# Get the model metrics
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(Y_test, tree_predictions))
print(confusion_matrix(Y_test,tree_predictions))

              precision    recall  f1-score   support

           0       0.81      0.75      0.78       130
           1       0.79      0.84      0.81       144

    accuracy                           0.80       274
   macro avg       0.80      0.79      0.79       274
weighted avg       0.80      0.80      0.79       274

[[ 97  33]
 [ 23 121]]


In [ ]:
#A support vector machine (SVM) is a type of supervised machine learning classification algorithm.
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
# Polynomial Kernel
#svclassifier  = SVC(kernel='poly', degree=8)
# Gaussian Kernel
#svclassifier = SVC(kernel='rbf')
# Sigmoid Kernel
#svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, Y_train)

In [1]:
svm_predictions = svclassifier.predict(X_test)

NameError: ignored

In [33]:
# Get the model metrics
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(Y_test, svm_predictions))
print(confusion_matrix(Y_test,svm_predictions))

              precision    recall  f1-score   support

           0       0.71      0.04      0.07       130
           1       0.53      0.99      0.69       144

    accuracy                           0.54       274
   macro avg       0.62      0.51      0.38       274
weighted avg       0.62      0.54      0.40       274

[[  5 125]
 [  2 142]]


In [34]:
#Check how weel the model did on the testing data set
print(svclassifier.score(X_test,Y_test))

0.5364963503649635
