<a href="https://colab.research.google.com/github/sergio-cabrales/python/blob/main/MachineLearning2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
pip install ta

In [35]:
# Import the libraries
import pandas as pd
import pandas_datareader as web
import numpy as np
import datetime
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from ta import add_all_ta_features
from ta.utils import dropna

In [36]:
# Get the stock quote
df = web.DataReader('AAPL', data_source='yahoo',start='2000-01-01', end='2021-01-01')
df

High         Low  ...       Volume   Adj Close
Date                                ...                         
2000-01-03    1.004464    0.907924  ...  535796800.0    0.860883
2000-01-04    0.987723    0.903460  ...  512377600.0    0.788302
2000-01-05    0.987165    0.919643  ...  778321600.0    0.799837
2000-01-06    0.955357    0.848214  ...  767972800.0    0.730621
2000-01-07    0.901786    0.852679  ...  460734400.0    0.765229
...                ...         ...  ...          ...         ...
2020-12-24  133.460007  131.100006  ...   54930100.0  131.773087
2020-12-28  137.339996  133.509995  ...  124486200.0  136.486053
2020-12-29  138.789993  134.339996  ...  121047300.0  134.668762
2020-12-30  135.990005  133.399994  ...   96452100.0  133.520477
2020-12-31  134.740005  131.720001  ...   99116600.0  132.492020

[5284 rows x 6 columns]

In [15]:
df[['High', 'Low', 'Open', 'Close', 'Volume', 'Adj Close', 'volume_adi',
       'volume_obv', 'volume_cmf', 'volume_fi', 'volume_mfi', 'volume_em',
       'volume_sma_em', 'volume_vpt', 'volume_nvi', 'volume_vwap',
       'volatility_atr', 'volatility_bbm', 'volatility_bbh', 'volatility_bbl',
       'volatility_bbw', 'volatility_bbp', 'volatility_bbhi',
       'volatility_bbli', 'volatility_kcc', 'volatility_kch', 'volatility_kcl',
       'volatility_kcw', 'volatility_kcp', 'volatility_kchi',
       'volatility_kcli', 'volatility_dcl', 'volatility_dch', 'volatility_dcm',
       'volatility_dcw', 'volatility_dcp', 'volatility_ui', 'trend_macd',
       'trend_macd_signal', 'trend_macd_diff', 'trend_sma_fast',
       'trend_sma_slow', 'trend_ema_fast', 'trend_ema_slow', 'trend_adx',
       'trend_adx_pos', 'trend_adx_neg', 'trend_vortex_ind_pos',
       'trend_vortex_ind_neg', 'trend_vortex_ind_diff', 'trend_trix',
       'trend_mass_index', 'trend_cci', 'trend_dpo', 'trend_kst',
       'trend_kst_sig', 'trend_kst_diff', 'trend_ichimoku_conv',
       'trend_ichimoku_base', 'trend_ichimoku_a', 'trend_ichimoku_b',
       'trend_visual_ichimoku_a', 'trend_visual_ichimoku_b', 'trend_aroon_up',
       'trend_aroon_down', 'trend_aroon_ind', 'trend_psar_up',
       'trend_psar_down', 'trend_psar_up_indicator',
       'trend_psar_down_indicator', 'trend_stc', 'momentum_rsi',
       'momentum_stoch_rsi', 'momentum_stoch_rsi_k', 'momentum_stoch_rsi_d',
       'momentum_tsi', 'momentum_uo', 'momentum_stoch',
       'momentum_stoch_signal', 'momentum_wr', 'momentum_ao', 'momentum_kama',
       'momentum_roc', 'momentum_ppo', 'momentum_ppo_signal',
       'momentum_ppo_hist', 'others_dr', 'others_dlr', 'others_cr']] = add_all_ta_features(df, open="Open", high="High", low="Low", close="Close", volume="Volume")
df

/usr/local/lib/python3.7/dist-packages/ta/trend.py:768: RuntimeWarning: invalid value encountered in double_scalars
  dip[i] = 100 * (self._dip[i] / self._trs[i])
/usr/local/lib/python3.7/dist-packages/ta/trend.py:772: RuntimeWarning: invalid value encountered in double_scalars
  din[i] = 100 * (self._din[i] / self._trs[i])


High         Low  ...  others_dlr     others_cr
Date                                ...                          
2000-01-03    1.004464    0.907924  ...         NaN      0.000000
2000-01-04    0.987723    0.903460  ...   -8.807741     -8.431001
2000-01-05    0.987165    0.919643  ...    1.452714     -7.091056
2000-01-06    0.955357    0.848214  ...   -9.051390    -15.131245
2000-01-07    0.901786    0.852679  ...    4.628127    -11.111100
...                ...         ...  ...         ...           ...
2020-12-24  133.460007  131.100006  ...    0.768265  13104.368406
2020-12-28  137.339996  133.509995  ...    3.514097  13576.632060
2020-12-29  138.789993  134.339996  ...   -1.340429  13394.529711
2020-12-30  135.990005  133.399994  ...   -0.856324  13279.466114
2020-12-31  134.740005  131.720001  ...   -0.773247  13176.408728

[5284 rows x 89 columns]

In [37]:
# Create the Target column
df['Target'] = np.where(df['Close'].shift(-1) > df['Close'], 1, 0)
# Show the data
df

High         Low        Open  ...       Volume   Adj Close  Target
Date                                            ...                                 
2000-01-03    1.004464    0.907924    0.936384  ...  535796800.0    0.860883       0
2000-01-04    0.987723    0.903460    0.966518  ...  512377600.0    0.788302       1
2000-01-05    0.987165    0.919643    0.926339  ...  778321600.0    0.799837       0
2000-01-06    0.955357    0.848214    0.947545  ...  767972800.0    0.730621       1
2000-01-07    0.901786    0.852679    0.861607  ...  460734400.0    0.765229       0
...                ...         ...         ...  ...          ...         ...     ...
2020-12-24  133.460007  131.100006  131.320007  ...   54930100.0  131.773087       1
2020-12-28  137.339996  133.509995  133.990005  ...  124486200.0  136.486053       0
2020-12-29  138.789993  134.339996  138.050003  ...  121047300.0  134.668762       0
2020-12-30  135.990005  133.399994  135.580002  ...   96452100.0  133.520477       0
2020-12-31  134.740005  131.720001  134.080002  ...   99116600.0  132.492020       0

[5284 rows x 7 columns]

In [38]:
#Remove the first 29 days of data
df = df[29:]
# Clean NaN values
df = dropna(df)
df

High         Low        Open  ...       Volume   Adj Close  Target
Date                                            ...                                 
2000-02-14    1.034598    0.969866    0.976004  ...  367539200.0    0.890684     1.0
2000-02-16    1.054688    1.001116    1.051339  ...  378246400.0    0.877706     1.0
2000-02-18    1.030134    0.989955    1.023438  ...  233441600.0    0.855596     1.0
2000-02-22    1.044085    0.952567    0.983259  ...  422296000.0    0.875303     1.0
2000-02-25    1.044643    0.983259    1.025112  ...  249144000.0    0.848866     1.0
...                ...         ...         ...  ...          ...         ...     ...
2020-12-16  128.369995  126.559998  127.410004  ...   98208600.0  127.619293     1.0
2020-12-18  129.100006  126.120003  128.960007  ...  192541500.0  126.471016     1.0
2020-12-21  128.309998  123.449997  125.019997  ...  121251600.0  128.038666     1.0
2020-12-23  132.429993  130.779999  132.160004  ...   88223700.0  130.764603     1.0
2020-12-24  133.460007  131.100006  131.320007  ...   54930100.0  131.773087     1.0

[2736 rows x 7 columns]

In [27]:
#Split tha data set into a feature or independent data set (X) and a Target or dependent data set (Y)
keep_columns = ['High', 'Low', 'Open', 'Close', 'Volume', 'Adj Close', 'volume_adi',
       'volume_obv', 'volume_cmf', 'volume_fi', 'volume_mfi', 'volume_em',
       'volume_sma_em', 'volume_vpt', 'volume_nvi', 'volume_vwap',
       'volatility_atr', 'volatility_bbm', 'volatility_bbh', 'volatility_bbl',
       'volatility_bbw', 'volatility_bbp', 'volatility_bbhi',
       'volatility_bbli', 'volatility_kcc', 'volatility_kch', 'volatility_kcl',
       'volatility_kcw', 'volatility_kcp', 'volatility_kchi',
       'volatility_kcli', 'volatility_dcl', 'volatility_dch', 'volatility_dcm',
       'volatility_dcw', 'volatility_dcp', 'volatility_ui', 'trend_macd',
       'trend_macd_signal', 'trend_macd_diff', 'trend_sma_fast',
       'trend_sma_slow', 'trend_ema_fast', 'trend_ema_slow', 'trend_adx',
       'trend_adx_pos', 'trend_adx_neg', 'trend_vortex_ind_pos',
       'trend_vortex_ind_neg', 'trend_vortex_ind_diff', 'trend_trix',
       'trend_mass_index', 'trend_cci', 'trend_dpo', 'trend_kst',
       'trend_kst_sig', 'trend_kst_diff', 'trend_ichimoku_conv',
       'trend_ichimoku_base', 'trend_ichimoku_a', 'trend_ichimoku_b',
       'trend_visual_ichimoku_a', 'trend_visual_ichimoku_b', 'trend_aroon_up',
       'trend_aroon_down', 'trend_aroon_ind', 'trend_psar_up',
       'trend_psar_down', 'trend_psar_up_indicator',
       'trend_psar_down_indicator', 'trend_stc', 'momentum_rsi',
       'momentum_stoch_rsi', 'momentum_stoch_rsi_k', 'momentum_stoch_rsi_d',
       'momentum_tsi', 'momentum_uo', 'momentum_stoch',
       'momentum_stoch_signal', 'momentum_wr', 'momentum_ao', 'momentum_kama',
       'momentum_roc', 'momentum_ppo', 'momentum_ppo_signal',
       'momentum_ppo_hist', 'others_dr', 'others_dlr', 'others_cr']
X = df[keep_columns].values
Y = df['Target'].values


In [39]:
X

array([], shape=(0, 89), dtype=float64)

In [29]:
Y

array([], dtype=float64)

In [24]:
# Split the data again but this time into 80% trading and 20% test
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state =2)

In [25]:
# Create and train the decision tree classsifier model
tree = DecisionTreeClassifier().fit(X_train,Y_train)

ValueError: ignored

In [ ]:
#Check how well the model did on the trainign data set
print(tree.score(X_train,Y_train))

1.0


In [ ]:
#Check how weel the model did on the testing data set
print(tree.score(X_test,Y_test))

0.510941960038059


In [ ]:
#Show the model tree predictions
tree_predictions = tree.predict(X_test)
print(tree_predictions)

[1 1 0 ... 0 0 1]


In [ ]:
Y_test

array([1, 0, 1, ..., 1, 1, 0])

In [ ]:
# Get the model metrics
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(Y_test, tree_predictions))
print(confusion_matrix(Y_test,tree_predictions))

              precision    recall  f1-score   support

           0       0.48      0.49      0.49       498
           1       0.54      0.53      0.53       553

    accuracy                           0.51      1051
   macro avg       0.51      0.51      0.51      1051
weighted avg       0.51      0.51      0.51      1051

[[243 255]
 [259 294]]


In [ ]:
#A support vector machine (SVM) is a type of supervised machine learning classification algorithm.
from sklearn.svm import SVC
# svclassifier = SVC(kernel='linear')
# Polynomial Kernel
#svclassifier  = SVC(kernel='poly', degree=8)
# Gaussian Kernel
svclassifier = SVC(kernel='rbf')
# Sigmoid Kernel
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
tree_predictions = svclassifier.predict(X_test)

In [ ]:
# Get the model metrics
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(Y_test, tree_predictions))
print(confusion_matrix(Y_test,tree_predictions))

              precision    recall  f1-score   support

           0       0.47      0.47      0.47       498
           1       0.53      0.53      0.53       553

    accuracy                           0.50      1051
   macro avg       0.50      0.50      0.50      1051
weighted avg       0.50      0.50      0.50      1051

[[233 265]
 [260 293]]


In [ ]:
#Check how weel the model did on the testing data set
print(svclassifier.score(X_test,Y_test))

0.5004757373929591
